import dynamic from 'next/dynamic'
const TraverseMap = dynamic(() => import('../src/components/Map'), {
    ssr: false,
})
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useClient } from 'providers/ClientProvider'
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
    const client = useClient()

    return (
        <div>
            <Head>
                <title>Hackify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {client.room && <div>Connected to room {client.room.name}</div>}
            <button
                onClick={async () => {
                    if (!client.connectToRoom) return
                    client.connectToRoom()
                }}
            >
                Connect
            </button>
            {<TraverseMap />}
        </div>
    )
}

export default Home
