import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useClient } from '../src/providers/ServerProvider'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    const client = useClient()
    return (
        <div className={styles.container}>
            <Head>
                <title>Hackify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <button
                onClick={async () => {
                    const rooms = await client.client?.joinOrCreate('my_room')
                    console.log('Rooms', rooms)
                }}
            >
                Connect
            </button>
        </div>
    )
}

export default Home
