import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useClient } from '../src/providers/ClientProvider'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
    const client = useClient()
    return (
        <div className={styles.container}>
            <Head>
                <title>Hackify</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {client.room && <div>Connected to room {client.room.name}</div>}
            <button
                onClick={async () => {
                    if (!client.connectToRoom) return
                    client.connectToRoom()
                }}
            >
                Connect
            </button>
        </div>
    )
}

export default Home
